Go upgrade  - 1.22.2
transcom/circleci-docker pull request #467
Opened 2024-04-29 14:07 UTC by deandreJones

# Description
Upgrade Go 1.20.6 to 122.2

## Changelog or Releases

Add the changelog or release URL for the tool being updated. Some examples below (delete the ones that do not apply
for clarity).

https://go.dev/doc/devel/release#go1.22.minor

2024-04-29 18:57 UTC, cameroncaci approved these changes
Great to see the build step working again

2024-04-29 19:01 UTC, cameroncaci requested changes

2024-04-29 19:01 UTC, cameroncaci commented on milmove-app/Dockerfile
> +  && bash setup_18.x \
We'll want to put the sha256 check back in place as this is an executed file

2024-05-06 19:21 UTC, josiahzimmerman-caci commented
@deandreJones   I think this is good to go to main. We can update the mymove app to the new image

2024-05-06 19:23 UTC, deandreJones commented
> @deandreJones I think this is good to go to main. We can update the mymove app to the new image

just need your stamp of approval

2024-05-06 19:23 UTC, josiahzimmerman-caci approved these changes

2024-05-06 19:24 UTC, merged